// ============================================================================
// HIMALAYAN BEAN ODYSSEY — SCIENTIFIC COFFEE DATA & TASTE METRIC ENGINE
// ============================================================================

window.COFFEE_DATA = {
  // 1) ARABICA COFFEE SPECIES VARIANTS
  varietals: [
    {
      id: "bourbon",
      name: "Bourbon (Red & Yellow)",
      lineage: "Natural mutation of Typica on Île Bourbon (Réunion, c. 1708)",
      nepalPrevalence: "~75% of Nepal's heritage hill plantings (Gulmi, Palpa, Syangja)",
      beanShape: "Rounder, plump, medium screen (15–17), curved center cut",
      optimalAltitude: "1,000m – 1,700m",
      icon: "🍒",
      color: "#d94e47",
      summary: "The backbone of Nepali specialty coffee. Produces higher cherry sucrose than Typica, yielding a deeply sweet, balanced cup with creamy caramel, roasted almond, and gentle malic-citric fruitiness.",
      geneticsNote: "Broad leaves with bronze-green tips; vigorous in Nepal's shaded smallholder agroforestry terraces.",
      baseScores: {
        acidity: 62,
        sweetness: 76,
        body: 68,
        fruityFloral: 58,
        chocoNut: 74,
        funkSpice: 32,
        bitterness: 24,
        clarity: 66
      },
      signatureNotes: ["Caramel", "Milk Chocolate", "Red Apple", "Roasted Almond"]
    },
    {
      id: "typica",
      name: "Typica (Heirloom)",
      lineage: "Foundational ancestral Coffea arabica from Southwestern Ethiopia & Yemen",
      nepalPrevalence: "~15% of older shade canopies in Kavre, Lalitpur & Nuwakot",
      beanShape: "Elongated, slender boat-shaped seed, open parchment fissure",
      optimalAltitude: "1,100m – 1,750m",
      icon: "🌿",
      color: "#4a8c5c",
      summary: "The mother of world Arabica. Low-yielding tall conical trees that channel energy into fewer cherries, delivering crystal-clean cup clarity, delicate jasmine-lemon elegance, and a silky tea-like finish.",
      geneticsNote: "Tall plant with wide lateral branching and copper-colored young leaf tips; prized for supreme cup cleanliness.",
      baseScores: {
        acidity: 68,
        sweetness: 70,
        body: 54,
        fruityFloral: 72,
        chocoNut: 56,
        funkSpice: 24,
        bitterness: 18,
        clarity: 84
      },
      signatureNotes: ["Lemon Verbena", "White Peach", "Cane Sugar", "Black Tea"]
    },
    {
      id: "caturra",
      name: "Caturra",
      lineage: "Single-gene dwarf mutation of Red Bourbon (Minas Gerais, Brazil, 1937)",
      nepalPrevalence: "Popular in modern terraced orchards across Kaski, Syangja & Ilam",
      beanShape: "Compact, dense medium bean with tightly closed center cut",
      optimalAltitude: "900m – 1,650m",
      icon: "🍋",
      color: "#e09f3e",
      summary: "A compact, high-producing Bourbon mutation with short internodes. Trades a bit of body for electric citric brightness, snappy pomelo/lime zest, and refreshing sweetness.",
      geneticsNote: "Dwarf stature allows closer terrace spacing on steep Himalayan slopes and easy hand-harvesting.",
      baseScores: {
        acidity: 78,
        sweetness: 64,
        body: 52,
        fruityFloral: 70,
        chocoNut: 50,
        funkSpice: 28,
        bitterness: 22,
        clarity: 76
      },
      signatureNotes: ["Bright Citrus", "Green Apple", "Honeydew", "Light Caramel"]
    },
    {
      id: "pacamara",
      name: "Pacamara",
      lineage: "Artificial cross: Pacas (dwarf Bourbon) × Maragogipe (giant Typica), El Salvador 1958",
      nepalPrevalence: "Specialty research & micro-lot trials (Pokhara ARS & Sindhupalchok)",
      beanShape: "Giant 'Elephant' bean (Screen 18–20+), broad oval profile",
      optimalAltitude: "1,200m – 1,800m",
      icon: "🐘",
      color: "#9b6b9e",
      summary: "An extraordinary large-bean hybrid combining dense sugar storage with exotic aromatics. Delivers a plush, creamy butterscotch mouthfeel layered with apricot, plum, and savory herbal spice.",
      geneticsNote: "Large thick leaves and massive cherries that require slow, high-elevation ripening to fill out the endosperm.",
      baseScores: {
        acidity: 72,
        sweetness: 74,
        body: 80,
        fruityFloral: 76,
        chocoNut: 64,
        funkSpice: 52,
        bitterness: 22,
        clarity: 64
      },
      signatureNotes: ["Butterscotch", "Ripe Plum", "Sweet Spice", "Dark Berry"]
    },
    {
      id: "tekisic",
      name: "Tekisic (Selected Bourbon)",
      lineage: "30-year mass selection of elite Red Bourbon by ISIC in El Salvador (1949–1977)",
      nepalPrevalence: "High-grade evaluation plots in Kaski, Nuwakot & Lalitpur",
      beanShape: "Small-to-medium ultra-dense seed with high lipid & sucrose content",
      optimalAltitude: "1,150m – 1,750m",
      icon: "🍯",
      color: "#c86d2d",
      summary: "Bred specifically for cup complexity at cool elevations. Famous for rich brown-sugar sweetness, velvety heavy body, ripe cherry cordial, and lingering cocoa nib warmth.",
      geneticsNote: "Retains classic Bourbon susceptibility to rust but rewards cool Himalayan microclimates with intense sugar density.",
      baseScores: {
        acidity: 66,
        sweetness: 82,
        body: 75,
        fruityFloral: 66,
        chocoNut: 76,
        funkSpice: 36,
        bitterness: 20,
        clarity: 72
      },
      signatureNotes: ["Brown Sugar", "Cherry Cordial", "Nougat", "Velvet Cocoa"]
    },
    {
      id: "gesha",
      name: "Gesha (Geisha)",
      lineage: "Wild Ethiopian forest landrace from Gori Gesha (1931), famed via Boquete, Panama",
      nepalPrevalence: "Ultra-rare experimental micro-lots above 1,500m in Sindhupalchok & Nuwakot",
      beanShape: "Long, slender, pointed canoe-shaped bean with delicate cell walls",
      optimalAltitude: "1,450m – 1,800m",
      icon: "🌸",
      color: "#5b9bd5",
      summary: "The pinnacle of aromatic Arabica. High concentrations of linalool and geraniol terpenes produce intoxicating jasmine blossom, bergamot Earl Grey, nectarine, and sparkling champagne-like acidity.",
      geneticsNote: "Thrives only in high, cool, mist-shrouded Himalayan ridges; struggles in warm low valleys.",
      baseScores: {
        acidity: 86,
        sweetness: 78,
        body: 48,
        fruityFloral: 94,
        chocoNut: 34,
        funkSpice: 38,
        bitterness: 14,
        clarity: 92
      },
      signatureNotes: ["Jasmine Blossom", "Bergamot", "White Nectarine", "Mandarin Zest"]
    }
  ],

  // 2) 10 COFFEE LOCATIONS IN NEPAL (600m to 1800m)
  // NOTE: `slopeAngle` and `slopeAspect` are strictly for visual sunlight & terrain demonstration
  // and are EXCLUDED from the numerical taste profile calculation as requested.
  nepalLocations: [
    {
      id: "tanahun_600",
      name: "Damauli Basin, Tanahun",
      shortName: "Tanahun",
      regionGroup: "western",
      province: "Gandaki Province",
      altitude: 600,
      slopeAngle: 12,
      slopeAspect: "SE (South-East)",
      sunlightHours: "8.4 hrs/day (Intense low-valley sun)",
      avgTempC: 23.8,
      maturationMonths: 5.8,
      beanDensity: "640 g/L (Soft / Open Fissure)",
      pinX: 498,
      pinY: 254,
      labelX: 488,
      labelY: 342,
      terroirStory: "Nestled near the confluence of the Seti and Madi rivers at 600m. Warm subtropical air speeds up cherry ripening in under 6 months, producing softer, lower-density beans with earthy, toasted grain, and low-acid nutty notes."
    },
    {
      id: "chitwan_750",
      name: "Kankada Hills, Chitwan-Makwanpur",
      shortName: "Chitwan",
      regionGroup: "central",
      province: "Bagmati Province",
      altitude: 750,
      slopeAngle: 16,
      slopeAspect: "S (South)",
      sunlightHours: "8.1 hrs/day (Warm Mahabharat foot-slope)",
      avgTempC: 22.7,
      maturationMonths: 6.2,
      beanDensity: "665 g/L (Medium-Low)",
      pinX: 536,
      pinY: 288,
      labelX: 556,
      labelY: 378,
      terroirStory: "Located on the gentle southern transition between the Siwalik hills and Mahabharat range. Warm days and mild nights yield a comforting, low-acidity cup dominated by roasted peanut, malt, and dark cocoa."
    },
    {
      id: "syangja_900",
      name: "Chapakot & Arjun Chaupari, Syangja",
      shortName: "Syangja",
      regionGroup: "western",
      province: "Gandaki Province",
      altitude: 900,
      slopeAngle: 21,
      slopeAspect: "E (East)",
      sunlightHours: "7.6 hrs/day (Morning sun, afternoon shade)",
      avgTempC: 21.5,
      maturationMonths: 6.7,
      beanDensity: "690 g/L (Medium)",
      pinX: 452,
      pinY: 250,
      labelX: 395,
      labelY: 336,
      terroirStory: "Rich red lateritic clay terraces shaded by banana and fodder trees. At 900m, cherries begin accumulating balanced sucrose, offering smooth milk chocolate, hazelnut, and mild sweet orange."
    },
    {
      id: "gulmi_1050",
      name: "Aapchaur, Gulmi (1938 Birthplace)",
      shortName: "Gulmi",
      regionGroup: "western",
      province: "Lumbini Province",
      altitude: 1050,
      slopeAngle: 24,
      slopeAspect: "NE (North-East)",
      sunlightHours: "7.2 hrs/day (Filtered valley mist)",
      avgTempC: 20.4,
      maturationMonths: 7.2,
      beanDensity: "712 g/L (Medium-High)",
      pinX: 402,
      pinY: 245,
      labelX: 326,
      labelY: 206,
      terroirStory: "The historic cradle of Nepali coffee, where hermit Hira Giri planted the first Arabica seeds from Myanmar in 1938. At 1,050m, cool river fog and fertile loam create classic Himalayan balance: caramel, walnut, and sweet lime."
    },
    {
      id: "palpa_1180",
      name: "Madanpokhara & Tansen Ridge, Palpa",
      shortName: "Palpa",
      regionGroup: "western",
      province: "Lumbini Province",
      altitude: 1180,
      slopeAngle: 28,
      slopeAspect: "SE (South-East)",
      sunlightHours: "7.0 hrs/day (Morning hillside warmth)",
      avgTempC: 19.4,
      maturationMonths: 7.6,
      beanDensity: "730 g/L (Firm)",
      pinX: 422,
      pinY: 268,
      labelX: 312,
      labelY: 298,
      terroirStory: "Perched along the breezy Tansen ridges. Cooler nights slow down cellular respiration in the coffee cherry, preserving malic acid (apple/pear notes) alongside honeyed graham cracker sweetness."
    },
    {
      id: "ilam_1250",
      name: "Fikkal, Kanyam & Mai Valley, Ilam",
      shortName: "Ilam",
      regionGroup: "eastern",
      province: "Koshi Province (Eastern Nepal)",
      altitude: 1250,
      slopeAngle: 26,
      slopeAspect: "SE (South-East)",
      sunlightHours: "6.9 hrs/day (Bay of Bengal mist & filtered sun)",
      avgTempC: 18.9,
      maturationMonths: 7.8,
      beanDensity: "740 g/L (High Density)",
      pinX: 884,
      pinY: 342,
      labelX: 836,
      labelY: 394,
      terroirStory: "Famous for mist-kissed Singalila ridges where moist Bay of Bengal air meets the eastern Himalayan foothills. Acidic, humus-rich soil shared with orthodox tea gardens imparts delicate floral muscatel, sweet citrus, and silky honeyed tea notes."
    },
    {
      id: "kaski_1300",
      name: "Begnas & Lekhnath Hills, Kaski",
      shortName: "Kaski",
      regionGroup: "western",
      province: "Gandaki Province",
      altitude: 1300,
      slopeAngle: 22,
      slopeAspect: "SW (South-West)",
      sunlightHours: "6.8 hrs/day (Lake-moderated sun)",
      avgTempC: 18.5,
      maturationMonths: 8.0,
      beanDensity: "748 g/L (High Density)",
      pinX: 468,
      pinY: 224,
      labelX: 438,
      labelY: 168,
      terroirStory: "Overlooking Begnas Lake with direct katabatic mountain breezes descending from the Annapurna massif. The diurnal temperature swing concentrates sugars and aromatic precursors."
    },
    {
      id: "panchthar_1380",
      name: "Phidim & Ranitar Hills, Panchthar",
      shortName: "Panchthar",
      regionGroup: "eastern",
      province: "Koshi Province (Eastern Nepal)",
      altitude: 1380,
      slopeAngle: 29,
      slopeAspect: "E (East)",
      sunlightHours: "6.7 hrs/day (Cool eastern ridge sunshine)",
      avgTempC: 17.9,
      maturationMonths: 8.2,
      beanDensity: "758 g/L (Strictly Hard Bean)",
      pinX: 862,
      pinY: 316,
      labelX: 762,
      labelY: 316,
      terroirStory: "Terraced eastern hill farms overlooking the Tamor and Kabeli river valleys. Cool mountain breezes and alder/cardamom shade canopies slow cherry ripening, producing crisp green apple, cane sugar, and sweet spice."
    },
    {
      id: "kavre_1420",
      name: "Panchkhal & Dhulikhel Rim, Kavre",
      shortName: "Kavre",
      regionGroup: "central",
      province: "Bagmati Province",
      altitude: 1420,
      slopeAngle: 31,
      slopeAspect: "E (East)",
      sunlightHours: "6.6 hrs/day (Crisp high-terrace light)",
      avgTempC: 17.6,
      maturationMonths: 8.3,
      beanDensity: "765 g/L (Strictly Hard Bean)",
      pinX: 650,
      pinY: 266,
      labelX: 736,
      labelY: 292,
      terroirStory: "Steep red-soil terraces east of Kathmandu Valley. At 1,420m, beans qualify as Strictly High Grown (SHG), exhibiting a tight center fissure, bright tangerine acidity, and cane sugar finish."
    },
    {
      id: "nuwakot_1550",
      name: "Belkotgadhi Highlands, Nuwakot",
      shortName: "Nuwakot",
      regionGroup: "central",
      province: "Bagmati Province",
      altitude: 1550,
      slopeAngle: 34,
      slopeAspect: "SE (South-East)",
      sunlightHours: "6.3 hrs/day (High mountain cloud cover)",
      avgTempC: 16.6,
      maturationMonths: 8.7,
      beanDensity: "782 g/L (Very Dense SHG)",
      pinX: 592,
      pinY: 244,
      labelX: 552,
      labelY: 184,
      terroirStory: "High above the Trishuli river gorge facing Ganesh Himal. Cherries take nearly 9 months to ripen, packing the seed endosperm with citric and phosphoric acids, berry aromatics, and floral honey."
    },
    {
      id: "taplejung_1620",
      name: "Fungling & Kanchenjunga Foothills, Taplejung",
      shortName: "Taplejung",
      regionGroup: "eastern",
      province: "Koshi Province (Far-Eastern Himalaya)",
      altitude: 1620,
      slopeAngle: 36,
      slopeAspect: "SW (South-West)",
      sunlightHours: "6.1 hrs/day (Glacial valley breeze & crisp UV)",
      avgTempC: 16.0,
      maturationMonths: 8.9,
      beanDensity: "790 g/L (Very Dense SHG)",
      pinX: 858,
      pinY: 284,
      labelX: 818,
      labelY: 218,
      terroirStory: "Cultivated in the dramatic shadow of Mt. Kanchenjunga (8,586m), the world's third-highest peak. Cold katabatic winds from the Kanchenjunga massif extend cherry maturation to nearly 9 months, yielding vibrant berry acidity, bergamot blossom, and crystalline sweetness."
    },
    {
      id: "lalitpur_1680",
      name: "Gimdi & Thuladurlung, Lalitpur",
      shortName: "Lalitpur",
      regionGroup: "central",
      province: "Bagmati Province",
      altitude: 1680,
      slopeAngle: 37,
      slopeAspect: "S (South)",
      sunlightHours: "6.0 hrs/day (Steep high-altitude terraces)",
      avgTempC: 15.6,
      maturationMonths: 9.0,
      beanDensity: "798 g/L (Ultra-Dense SHG)",
      pinX: 612,
      pinY: 274,
      labelX: 652,
      labelY: 352,
      terroirStory: "Remote organic-certified southern ridges of Lalitpur. Grown under silver oak and alder shade at 1,680m, producing dense, hard beans with apricot, jasmine tea, and sparkling acidity."
    },
    {
      id: "sindhupalchok_1800",
      name: "Helambu & Melamchi Ridge, Sindhupalchok",
      shortName: "Sindhupalchok",
      regionGroup: "central",
      province: "Bagmati Province",
      altitude: 1800,
      slopeAngle: 41,
      slopeAspect: "SW (South-West)",
      sunlightHours: "5.7 hrs/day (Alpine mist & intense UV)",
      avgTempC: 14.5,
      maturationMonths: 9.4,
      beanDensity: "815 g/L (Extreme High-Altitude Density)",
      pinX: 642,
      pinY: 236,
      labelX: 672,
      labelY: 174,
      terroirStory: "The upper frontier of Himalayan coffee cultivation at 1,800m beneath Jugal Himal. Near-freezing winter nights force the coffee tree to pump sucrose antifreeze into the cherry, creating explosive florals, bergamot, and electric citrus."
    }
  ],

  // 3) FERMENTATION & POST-HARVEST PROCESSING METHODS
  fermentations: [
    {
      id: "pulped",
      name: "Pulped / Washed (Wet Process)",
      subtitle: "Skin & mucilage completely removed via tank fermentation & mountain spring washing",
      icon: "💧",
      color: "#5b9bd5",
      fermentTime: "18–36 hrs in clean water tank",
      dryingTime: "8–12 days on raised beds",
      keptLayers: ["Endocarp (Parchment)", "Silver Skin", "Endosperm (Green Bean)"],
      removedLayers: ["Exocarp (Outer Skin)", "Mesocarp (Sticky Mucilage)"],
      microbiology: "Natural pectinolytic enzymes and Leuconostoc bacteria break down pectin in the mucilage so it washes off cleanly. Almost no external fruit sugars diffuse into the seed.",
      sensoryImpact: "Purest expression of varietal & Nepal altitude terroir. Maximizes cup clarity and crisp malic/citric acidity while keeping body light and silky.",
      modifiers: {
        acidity: +12,
        sweetness: -2,
        body: -10,
        fruityFloral: +6,
        chocoNut: 0,
        funkSpice: -12,
        bitterness: -4,
        clarity: +22
      },
      flavorNotes: ["Crisp Citrus", "Washed Florals", "Clean Tea Finish"]
    },
    {
      id: "honey",
      name: "Honey Process (Pulped Natural)",
      subtitle: "Outer skin pulped off, but sticky sugar-rich fruit mucilage left to dry on the bean",
      icon: "🍯",
      color: "#e09f3e",
      fermentTime: "Open-air mucilage caramelization during drying",
      dryingTime: "14–18 days (frequent turning)",
      keptLayers: ["50–80% Mesocarp (Honey Mucilage)", "Endocarp (Parchment)", "Green Bean"],
      removedLayers: ["Exocarp (Outer Cherry Skin)"],
      microbiology: "Named after how sticky the beans feel (like 'miel' / honey). As the mucilage dehydrates in the Himalayan sun, reducing sugars and amino acids migrate across the parchment.",
      sensoryImpact: "Bridges the clarity of Washed with the body of Natural. Amplifies brown-sugar & stone-fruit sweetness, rounds out sharp acidity, and builds a creamy mouthfeel.",
      modifiers: {
        acidity: +2,
        sweetness: +18,
        body: +10,
        fruityFloral: +10,
        chocoNut: +8,
        funkSpice: +6,
        bitterness: -2,
        clarity: +4
      },
      flavorNotes: ["Wildflower Honey", "Ripe Apricot", "Toffee", "Yellow Plum"]
    },
    {
      id: "sundried",
      name: "Sundried / Natural (Dry Process)",
      subtitle: "Whole intact coffee cherries dried slowly in the sun with skin and fruit pulp intact",
      icon: "☀️",
      color: "#d47a27",
      fermentTime: "Continuous intra-cherry enzymatic fermentation",
      dryingTime: "22–30 days on raised solar tables",
      keptLayers: ["Exocarp (Skin)", "100% Mesocarp (Pulp/Mucilage)", "Parchment", "Green Bean"],
      removedLayers: ["None until final dry hulling!"],
      microbiology: "Wild yeasts (Saccharomyces, Pichia) ferment fructose and glucose inside the shrinking cherry skin, generating ethyl esters that soak deep into the seed endosperm.",
      sensoryImpact: "Produces a heavy, syrupy body and bold blueberry, strawberry jam, and tropical fruit notes, while softening perceived acidity and lowering transparency.",
      modifiers: {
        acidity: -8,
        sweetness: +15,
        body: +20,
        fruityFloral: +20,
        chocoNut: +4,
        funkSpice: +22,
        bitterness: +2,
        clarity: -16
      },
      flavorNotes: ["Blueberry Jam", "Dried Fig", "Red Wine", "Syrupy Cocoa"]
    },
    {
      id: "anaerobic",
      name: "Anaerobic Fermentation (Sealed Bioreactor)",
      subtitle: "Pressurized oxygen-free tank fermentation with CO₂ valve before solar drying",
      icon: "🧪",
      color: "#9b6b9e",
      fermentTime: "48–96 hrs in sealed O₂-free bioreactor",
      dryingTime: "15–22 days controlled slow dry",
      keptLayers: ["Whole Cherry or Pulped Mucilage in CO₂ Broth", "Parchment", "Green Bean"],
      removedLayers: ["Oxygen purged via one-way CO₂ bubbler valve"],
      microbiology: "Without oxygen, Lactic Acid Bacteria (LAB) dominate, converting sugars into lactic acid and volatile esters (ethyl acetate, isoamyl acetate) that permanently alter bean chemistry.",
      sensoryImpact: "Unlocks exotic, high-intensity aromatics: passionfruit, Lychee, cinnamon bark, winey funk, and a lush, creamy yogurt-like lactic acidity.",
      modifiers: {
        acidity: +10,
        sweetness: +14,
        body: +15,
        fruityFloral: +26,
        chocoNut: -6,
        funkSpice: +34,
        bitterness: 0,
        clarity: -8
      },
      flavorNotes: ["Passionfruit", "Cinnamon Spice", "Hibiscus Wine", "Candied Banana"]
    }
  ],

  // 4) ROASTING SPECTRUM BENCHMARKS (0 to 100 scale)
  roastBenchmarks: [
    {
      id: "cinnamon",
      name: "Cinnamon / Ultra-Light",
      range: [0, 18],
      sliderVal: 10,
      tempC: 196,
      agtron: 85,
      beanColor: "#b89356",
      crackStage: "Start of 1st Crack",
      massLoss: "11.5%",
      expansion: "+18%",
      chemistry: "Drying complete; early Maillard reaction begins. Chlorogenic acids remain intact; sucrose has not yet caramelized.",
      profileNote: "Extremely high, sharp acidity; herbaceous, floral, and toasted grain notes; thin body; 100% origin transparency."
    },
    {
      id: "light",
      name: "Light Roast (City-)",
      range: [19, 36],
      sliderVal: 28,
      tempC: 205,
      agtron: 70,
      beanColor: "#9c6b34",
      crackStage: "End of 1st Crack (💥)",
      massLoss: "13.5%",
      expansion: "+32%",
      chemistry: "Endothermic-to-exothermic steam burst (First Crack). Maillard amino-sugar reactions create furans and pyrazines while preserving volatile terpenes.",
      profileNote: "Vibrant citrus & stone-fruit acidity, jasmine/floral clarity, sweet tea body. Best showcase for high-altitude Nepal varietals."
    },
    {
      id: "med_light",
      name: "Medium-Light (City)",
      range: [37, 54],
      sliderVal: 45,
      tempC: 213,
      agtron: 60,
      beanColor: "#7d4b22",
      crackStage: "Post-1st Crack Development",
      massLoss: "15.0%",
      expansion: "+44%",
      chemistry: "Sucrose caramelization accelerates (~208°C+). Organic acids begin mellowing while caramel, honey, and milk chocolate compounds peak.",
      profileNote: "Harmonious sweet spot: bright fruit meets rich caramel, honey, and milk chocolate with a rounded, silky mouthfeel."
    },
    {
      id: "medium",
      name: "Medium Roast (Full City)",
      range: [55, 71],
      sliderVal: 63,
      tempC: 220,
      agtron: 50,
      beanColor: "#5e3315",
      crackStage: "Onset of 2nd Crack",
      massLoss: "16.8%",
      expansion: "+56%",
      chemistry: "Peak Maillard & caramelization; chlorogenic acids break down into caffeic & quinic lactones. Delicate floral terpenes begin volatilizing.",
      profileNote: "Full body, roasted hazelnut, dark cocoa, bittersweet toffee, and gentle rounded acidity."
    },
    {
      id: "med_dark",
      name: "Medium-Dark (Vienna)",
      range: [72, 86],
      sliderVal: 78,
      tempC: 228,
      agtron: 40,
      beanColor: "#3e1f0d",
      crackStage: "Rolling 2nd Crack (💥💥)",
      massLoss: "18.5%",
      expansion: "+68%",
      chemistry: "Cellulose matrix fractures (Second Crack), pushing internal lipids/oils to the bean surface. Pyrolysis forms bittersweet phenylindanes.",
      profileNote: "Heavy syrupy body, bittersweet 80% dark chocolate, clove/nutmeg spice, low acidity; roast character begins overshadowing terroir."
    },
    {
      id: "dark",
      name: "Dark Roast (French / Italian)",
      range: [87, 100],
      sliderVal: 94,
      tempC: 238,
      agtron: 28,
      beanColor: "#211007",
      crackStage: "Late 2nd Crack / Surface Oil Sheen",
      massLoss: "21.0%",
      expansion: "+78%",
      chemistry: "Extensive dry distillation and carbonization. Sugars are largely pyrolyzed; phenylindanes and smoky phenols dominate.",
      profileNote: "Intense smoky, charred wood, molasses, and espresso-roast bitterness; near-zero acidity; origin differences almost completely masked."
    }
  ],

  // 5) GRINDING & EXTRACTION METHODS
  brewMethods: [
    {
      id: "espresso",
      name: "Espresso (9 Bar Pressure)",
      category: "Fine Grind / High-Pressure Percolation",
      icon: "☕",
      idealMicrons: [220, 380],
      sweetSpotMicron: 300,
      defaultTimeSec: 28,
      timeRangeSec: [15, 45],
      defaultTempC: 93,
      ratioLabel: "1:2 (18g in → 36g liquid)",
      filterType: "Precision Perforated Metal Basket",
      science: "9 bars of hydraulic pressure force hot water through a tightly packed puck of fine coffee in ~28 seconds. Emulsifies coffee lipids into golden crema, amplifying body, sweetness, and intensity.",
      modifiers: {
        body: +18,
        clarity: -10,
        acidity: +4,
        sweetness: +6,
        bitterness: +6
      }
    },
    {
      id: "aeropress",
      name: "AeroPress / Moka Hybrid",
      category: "Medium-Fine Grind / Gentle Pressure",
      icon: "🧪",
      idealMicrons: [400, 580],
      sweetSpotMicron: 480,
      defaultTimeSec: 90,
      timeRangeSec: [45, 160],
      defaultTempC: 90,
      ratioLabel: "1:12 (Immersion + Air Pressure)",
      filterType: "Micro-Paper or Metal Disk",
      science: "Combines short immersion steeping with ~1.5 bar pneumatic plunger pressure. Extracts rich sugars and fruit notes with low bitterness and medium-full velvet body.",
      modifiers: {
        body: +6,
        clarity: +6,
        acidity: +4,
        sweetness: +10,
        bitterness: -4
      }
    },
    {
      id: "v60",
      name: "Pour-Over Filter (V60 / Chemex)",
      category: "Medium to Medium-Coarse / Gravity Percolation",
      icon: "⏳",
      idealMicrons: [550, 850],
      sweetSpotMicron: 680,
      defaultTimeSec: 180,
      timeRangeSec: [100, 270],
      defaultTempC: 94,
      ratioLabel: "1:16 (15g coffee → 240ml water)",
      filterType: "Bleached Cellulose Paper Filter",
      science: "Fresh hot water continuously percolates through the coffee bed by gravity. The paper fibers trap insoluble fines and diterpene oils (cafestol), creating crystal-clear separation of floral & fruit notes.",
      modifiers: {
        body: -12,
        clarity: +20,
        acidity: +10,
        sweetness: +4,
        bitterness: -6
      }
    },
    {
      id: "frenchpress",
      name: "French Press (Full Immersion)",
      category: "Coarse Grind / Steeped Immersion",
      icon: "🫖",
      idealMicrons: [850, 1150],
      sweetSpotMicron: 1000,
      defaultTimeSec: 240,
      timeRangeSec: [120, 360],
      defaultTempC: 93,
      ratioLabel: "1:15 (Steeped 4 Minutes)",
      filterType: "Woven Stainless Steel Mesh Plunger",
      science: "Coarse grounds steep freely in water for 4 minutes. Because diffusion slows as water saturates with solubles, coarse particles prevent harsh over-extraction while the metal mesh lets all natural oils into the cup.",
      modifiers: {
        body: +15,
        clarity: -16,
        acidity: -6,
        sweetness: +6,
        bitterness: +4
      }
    }
  ],

  // 6) BARISTA CHALLENGES / CUSTOMER QUESTS
  quests: [
    {
      id: "freeplay",
      name: "Free Lab (Open Exploration)",
      icon: "🧭",
      description: "Experiment freely with any Nepal origin, varietal, fermentation, roast, and grind to discover its sensory signature.",
      target: null
    },
    {
      id: "himalayan_gesha",
      name: "Quest 1: The High-Altitude Floral Filter",
      icon: "🌸",
      description: "Craft an ultra-clean, sparkling floral & citrus tea-like cup (Target: Acidity ≥ 80, Fruity/Floral ≥ 82, Clarity ≥ 80, Bitterness ≤ 25).",
      hint: "Try Gesha or Typica above 1,500m (Nuwakot/Lalitpur/Sindhupalchok), Washed/Pulped process, Light Roast, and Medium-Coarse V60 Pour-Over!",
      target: {
        acidity: { min: 80 },
        fruityFloral: { min: 82 },
        clarity: { min: 80 },
        bitterness: { max: 25 }
      }
    },
    {
      id: "funky_anaerobic",
      name: "Quest 2: Exotic Anaerobic Fruit Bomb",
      icon: "🧪",
      description: "Create an experimental tropical & winey explosion with lush sweetness (Target: Funk/Spice ≥ 65, Fruity/Floral ≥ 78, Sweetness ≥ 75).",
      hint: "Pair Pacamara or Bourbon at high altitude with Anaerobic Fermentation, Light-to-Medium-Light Roast, and AeroPress or V60.",
      target: {
        funkSpice: { min: 65 },
        fruityFloral: { min: 78 },
        sweetness: { min: 75 }
      }
    },
    {
      id: "gulmi_espresso",
      name: "Quest 3: Velvety Chocolate-Caramel Espresso",
      icon: "☕",
      description: "Pull a syrupy, comforting classic espresso with rich chocolate/nut and heavy body (Target: Body ≥ 78, Choco/Nut ≥ 72, Sweetness ≥ 70, EY 18.5%–21.5%).",
      hint: "Try Bourbon or Tekisic from Gulmi/Palpa/Syangja (900–1,200m), Honey or Natural process, Medium to Medium-Dark Roast, and Fine Grind (~300 µm) on Espresso!",
      target: {
        body: { min: 78 },
        chocoNut: { min: 72 },
        sweetness: { min: 70 },
        eyBalanced: true
      }
    }
  ]
};
